# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-audit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "deb0b04f33c4a490e7020a4412c9534a94088e58a9adb5b8fae4d9049558fc7d"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51fd62bc9608e87e729dd9703ccad0ab0acefc110aec855cae467f278e7de470"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5aba09eeadc3813e92e42327b2d69b715b65aa071779edfcc1f9ccc6bab6ea47"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5937b51289f88226c672d79662af82c546d364c76295695659f95a2fde71c674"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "code-audit"
  desc "Cross-cutting structural analysis of codebases."
  homepage "https://github.com/jakebromberg/code-audit-pipeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-audit"

  # No zap stanza required

end
