# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-audit" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "ab43cbf82bad16586dd384ddc73e23e05bcb6fbc85b66d7098a4add4abab0227"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0759080728c5721b27284de17c789d090d7ac567e46bd6cfdc87390ed7cd0643"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b56c36f94543871f499d35d1d22aef852fac2461f12b4bfdf639f46394d2db0d"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ca63d24636045129b2f595fd64d68b520e04a621a578990fc3ef5a005719669"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "code-audit"
  desc "Cross-cutting structural analysis of codebases."
  homepage "https://github.com/jakebromberg/code-audit-pipeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-audit"

  # No zap stanza required

end
