# This file was generated by GoReleaser. DO NOT EDIT.
cask "code-audit" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "127d54af37765f5bdbb886f0570fb3b2194b87493f57aa7f3efe7ec1ca24d595"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b03c4a96ec8d00057a7816df3c8a07f51b8a0110fc25ad44775d07937b1133bf"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ac6b61c5181cfaa098c7f8b7285d8489e0d88cf559c68a27302bdb419b8a30c"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba90f8851ab78f1e1596e0db85a88c269ffe02ae9117cf1d42aa016ac2b3c14a"
      url "https://github.com/jakebromberg/code-audit-pipeline/releases/download/v#{version}/code-audit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "code-audit"
  desc "Cross-cutting structural analysis of codebases."
  homepage "https://github.com/jakebromberg/code-audit-pipeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "code-audit"

  # No zap stanza required

end
